export interface Customer {
	CODIGO: number;
	RAZAO: string;
	FANTASIA: string | null;
	PESSOA: "FIS" | "JUR" | null;
	ATIVO: "SIM" | "NAO" | null;
	CPF_CNPJ: string | null;
	IE_RG: string | null;
	GRUPO: number | null;
	END_RUA: string | null;
	CIDADE: string | null;
	BAIRRO: string | null;
	ESTADO: string | null;
	CEP: string | null;
	COMPLEMENTO: string | null;
	AREA1: number | null;
	AREA2: number | null;
	AREA3: number | null;
	AREAFAX: number | null;
	FONE1: string | null;
	FONE2: string | null;
	FONE3: string | null;
	FAX: string | null;
	DESC_FONE1: string | null;
	DESC_FONE2: string | null;
	DESC_FONE3: string | null;
	DESCFAX: string | null;
	EMAIL: string | null;
	WEBSITE: string | null;
	DATACAD: string | null;
	STATUS_CAD: string | null;
	OBS_ADMIN: string | null;
	OBS_OPERADOR: string | null;
	ORIGEM: number | null;
	OPERADOR: number | null;
	COD_MIDIA: number | null;
	COD_ERP: string | null;
	BLOCK_COMPRAS: "SIM" | "NAO" | null;
	COD_UNIDADE: number | null;
	SALDO_DISPONIVEL: number | null;
	SALDO_LIMITE: number | null;
	POTENCIAL: number | null;
	DATA_ULT_COMPRA: string | null;
	SEGMENTO: number | null;
	ULTI_RESULTADO: string | null;
	DT_AGENDAMENTO: string | null;
	COD_CAMPANHA: number | null;
	COD_RESULTADO: number | null;
	CONTATO_MAIL: string | null;
	ATUALIZADOR: "CADASTRO" | "ATUALIZAÇÃO" | null;
	OPERADOR_LOGIN: string | null;
	OBS_FONE1: string | null;
	OBS_FONE2: string | null;
	OBS_FONE3: string | null;
	NR_FUNCIONARIOS: number | null;
	EMAIL2: string | null;
	OBS_CLIENTES: string | null;
	VENCIMENTO_LIMITE_CREDITO: string | null;
	PERIODO_RECOMPRA: number;
	DT_ULTIMO_ORCAMENTO_VENDA: string | null;
	POSSUI_ORCAMENTO: "S" | "N" | null;
	POSSUI_VENDA: "S" | "N" | null;
	CODIGOPRINCIPAL: number | null;
	SETOR: number | null;
}

export interface CreateCustomerDTO {
	RAZAO: string;
	CPF_CNPJ?: string | null;
	FANTASIA?: string | null;
	PESSOA?: "FIS" | "JUR" | null;
	ATIVO?: "SIM" | "NAO" | null;
	CIDADE?: string | null;
	ESTADO?: string | null;
	COD_ERP?: string | null;
	SETOR?: number | null;
}
export type UpdateCustomerDTO = Partial<CreateCustomerDTO>;
