export interface Customer {
    CODIGO: number;
    RAZAO: string;
    FANTASIA: string;
    PESSOA: 'FIS' | 'JUR' | null;
    ATIVO: 'SIM' | 'NAO' | null;
    CPF_CNPJ: string;
    IE_RG: string;
    GRUPO: number;
    END_RUA: string;
    CIDADE: string;
    BAIRRO: string;
    ESTADO: string;
    CEP: string;
    COMPLEMENTO: string;
    AREA1: number;
    AREA2: number;
    AREA3: number;
    AREAFAX: number;
    FONE1: string;
    FONE2: string;
    FONE3: string;
    FAX: string;
    DESC_FONE1: string;
    DESC_FONE2: string;
    DESC_FONE3: string;
    DESCFAX: string;
    EMAIL: string;
    WEBSITE: string;
    DATACAD: Date;
    STATUS_CAD: string;
    OBS_ADMIN: string;
    OBS_OPERADOR: string;
    ORIGEM: number;
    OPERADOR: number;
    COD_MIDIA: number;
    COD_ERP: string;
    BLOCK_COMPRAS: 'SIM' | 'NAO' | null;
    COD_UNIDADE: number;
    SALDO_DISPONIVEL: number;
    SALDO_LIMITE: number;
    POTENCIAL: number;
    DATA_ULT_COMPRA: Date;
    SEGMENTO: number;
    ULTI_RESULTADO: Date;
    DT_AGENDAMENTO: Date;
    COD_CAMPANHA: number;
    COD_RESULTADO: number;
    CONTATO_MAIL: string;
    ATUALIZADOR: 'CADASTRO' | 'ATUALIZAÇÃO' | null;
    OPERADOR_LOGIN: string;
    OBS_FONE1: string;
    OBS_FONE2: string;
    OBS_FONE3: string;
    NR_FUNCIONARIOS: number;
    EMAIL2: string;
    OBS_CLIENTES: string;
    VENCIMENTO_LIMITE_CREDITO: Date;
    PERIODO_RECOMPRA: number;
    DT_ULTIMO_ORCAMENTO_VENDA: Date;
    POSSUI_ORCAMENTO: 'S' | 'N' | null;
    POSSUI_VENDA: 'S' | 'N' | null;
    CODIGOPRINCIPAL: number;
    SETOR: number;
}

export type CreateCustomerDTO = Pick<Customer, "RAZAO" | "FANTASIA" | "CPF_CNPJ" | "PESSOA" | "CIDADE" | "ESTADO" | "COD_ERP">;
export type UpdateCustomerDTO = Partial<CreateCustomerDTO>;